# Default values for my-dadjokes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: dadjokes
namespace: sre-techtask

deployment:
  replicaCount: 2
  maxSurge: 1
  maxUnavailable: 0

containers:
  image:
    repository: docker.io/yesinteractive/dadjokes
    pullPolicy: IfNotPresent
    containerPort: 8100
    limitsCPU: 500m
    requestsCPU: 200m

service:
  type: NodePort
  port: 8100

ingress:
  host: damyan-example.com
  enabled: false
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUAvarageUtilization: 30
 

